### ISSUE TITLE
涛哥好，发现两个小瑕疵

### ISSUE THREAD

**Issue by Yunx-x** [kymjs/KotlinPrimer#2]
在看视频学习的时候发现了两个小瑕疵的地方。虽然不影响学习过程，但是看着别扭。。。
1. 第2讲的3分40秒处，口误了
![image](https://user-images.githubusercontent.com/16937515/42798737-b967f4b8-89c7-11e8-8864-f198f127d3bf.png)
2. 第4讲，练习题是不是写错了。。
![image](https://user-images.githubusercontent.com/16937515/42798806-0318fb5c-89c8-11e8-8d84-15f38de71b8b.png)

**Comment by kymjs** [comment]
确实确实，谢谢指正。可惜如果是文字还好，视频没办法改正，只能请见谅了。
