### ISSUE TITLE
环境的问题

### ISSUE THREAD

**Issue by YamingZhao** [kymjs/KotlinPrimer#4]
为什么按照第二讲极客视频中搭建的Hellokt.kt文件，无法在idea里面点击run？
到底IDE里面需要配置什么？涛哥不讲这个感觉好多人都会碰到问题。因为现在光ide一般就有idea和AS两种，到底要add 什么configuration才能run一个kotlin项目？
![screen shot 2018-11-27 at 9 55 38 pm](https://user-images.githubusercontent.com/21186712/49086487-96db4e00-f28f-11e8-85ce-305d7034cebc.png)
![screen shot 2018-11-27 at 9 59 03 pm](https://user-images.githubusercontent.com/21186712/49086519-ace90e80-f28f-11e8-85b0-da6b29cdf2a4.png)

**Comment by kymjs** [comment]
不用加任何配置的啊，第一步 File->New Project

![image](https://user-images.githubusercontent.com/5780230/49123719-a2149500-f2f4-11e8-81b2-de9fe97178b3.png)

第二步 选 kotlin 工程，接下来输自己的项目信息就可以了
![image](https://user-images.githubusercontent.com/5780230/49123755-bbb5dc80-f2f4-11e8-9cb1-62418eb114ce.png)

**Comment by kymjs** [comment]
还有，你的 Main 函数参数写的也不标准。
1.3以后，可以不写参数，之前的版本需要用`Array<String>`作为参数类型
